import { Inter, Manrope, Roboto_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const groteskLight = localFont({
  src: "../public/fonts/LabilGrotesk-Light.woff2",
  variable: "--font-grotesk-light",
});
const groteskRegular = localFont({
  src: "../public/fonts/LabilGrotesk-Regular.woff2",
  variable: "--font-grotesk-regular",
});
const groteskMedium = localFont({
  src: "../public/fonts/LabilGrotesk-Medium.woff2",
  variable: "--font-grotesk-medium",
});
const groteskBold = localFont({
  src: "../public/fonts/LabilGrotesk-Bold.woff2",
  variable: "--font-grotesk-bold",
});

const bitcountGrid = localFont({
  src: "../public/fonts/BitcountGridDouble_Cursive-Light.ttf",
  variable: "--font-bitcount-grid",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${groteskLight.variable} ${groteskRegular.variable} ${groteskMedium.variable} ${groteskBold.variable} ${bitcountGrid.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
